name: Gems - Release to RubyGems
on: # yamllint disable-line rule:truthy
  release:
    # It's fine to trigger on every release because if we tag a release w/o
    # bumping the Gem version, RubyGems will reject it with an error that the
    # version is already live.
    types: [published]

jobs:
  release-gems:
    name: Release gems to rubygems.org
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: ruby/setup-ruby@f26937343756480a8cb3ae1f623b9c8d89ed6984 # v1.196.0
      - run: |
          [ -d ~/.gem ] || mkdir ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY_WITH_SCOPE_LIMITED_TO_PUSH }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem install rake && rake gems:release
